// <auto-generated />
using CinemaApp.ContextBd;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaApp.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20251126145418_UpdateMovieModel3")]
    partial class UpdateMovieModel3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaApp.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BoxOfficeReceipts")
                        .HasColumnType("bigint");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoxOfficeReceipts = 2923706026L,
                            Country = "США",
                            Genre = "Sci-Fi",
                            Price = 11.00m,
                            ReleaseYear = 2009,
                            Title = "Аватар"
                        },
                        new
                        {
                            Id = 2,
                            BoxOfficeReceipts = 2799439100L,
                            Country = "США",
                            Genre = "Superhero",
                            Price = 12.00m,
                            ReleaseYear = 2019,
                            Title = "Мстители: Конец игры"
                        },
                        new
                        {
                            Id = 3,
                            BoxOfficeReceipts = 1495696292L,
                            Country = "США",
                            Genre = "Action",
                            Price = 11.50m,
                            ReleaseYear = 2022,
                            Title = "Top Gun: Maverick"
                        },
                        new
                        {
                            Id = 4,
                            BoxOfficeReceipts = 1074458282L,
                            Country = "США",
                            Genre = "Thriller/Drama",
                            Price = 10.50m,
                            ReleaseYear = 2019,
                            Title = "Джокер"
                        },
                        new
                        {
                            Id = 5,
                            BoxOfficeReceipts = 1342359942L,
                            Country = "Великобритания",
                            Genre = "Fantasy",
                            Price = 10.20m,
                            ReleaseYear = 2011,
                            Title = "Гарри Поттер и дары смерти: Часть 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
